// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    DialogWelcome: typeof import('./src/components/DialogWelcome.vue')['default']
    Hobby: typeof import('./src/components/Hobby.vue')['default']
  }
}

export {}
